name 'windows_license'
maintainer 'James Massardo'
maintainer_email 'james@dxrf.com'
license 'Apache-2.0'
description 'Custom Chef Resource that provides a simple way to Activate Windows nodes'
version '0.1.0'
chef_version '>= 14.0'
issues_url 'https://github.com/jmassardo/windows_license/issues'
source_url 'https://github.com/jmassardo/windows_license'
