name 'windows_license'
maintainer 'James Massardo'
maintainer_email 'james@dxrf.com.com'
license 'All Rights Reserved'
description 'Installs/Configures windows_license'
version '0.1.0'
chef_version '>= 14.0'
issues_url 'https://github.com/jmassardo/windows_license/issues'
source_url 'https://github.com/jmassardo/windows_license'
